// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templ

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CaelumContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-4\"><style>\n\t\t\t.verse-caelum-panel {\n\t\t\t\tmin-width: 0;\n\t\t\t\tpadding: 1rem 1.1rem;\n\t\t\t}\n\n\t\t\t.verse-caelum-prompt {\n\t\t\t\tdisplay: flex;\n\t\t\t\tmin-height: 12.5rem;\n\t\t\t\talign-items: center;\n\t\t\t\tpadding: 1.05rem 1.1rem;\n\t\t\t\tborder: 1px solid rgb(23 23 23);\n\t\t\t\tborder-radius: 1.2rem;\n\t\t\t\tbackground: linear-gradient(180deg, rgba(18, 18, 18, 0.92) 0%, rgba(10, 10, 10, 0.98) 100%);\n\t\t\t}\n\n\t\t\t.verse-caelum-prompt-output {\n\t\t\t\tfont-family: Georgia, Cambria, \"Times New Roman\", Times, serif;\n\t\t\t\tfont-size: 1.35rem;\n\t\t\t\tline-height: 1.42;\n\t\t\t\tcolor: rgb(216 180 254);\n\t\t\t\toverflow-wrap: anywhere;\n\t\t\t}\n\n\t\t\t.verse-caelum-actions {\n\t\t\t\tdisplay: flex;\n\t\t\t\tflex-wrap: wrap;\n\t\t\t\tgap: 0.75rem;\n\t\t\t\tpadding-top: 0.85rem;\n\t\t\t}\n\n\t\t\t@media (max-width: 639px) {\n\t\t\t\t.verse-caelum-panel {\n\t\t\t\t\tpadding: 1rem;\n\t\t\t\t}\n\n\t\t\t\t.verse-caelum-prompt {\n\t\t\t\t\tmin-height: 10.75rem;\n\t\t\t\t\tpadding: 1rem;\n\t\t\t\t}\n\n\t\t\t\t.verse-caelum-prompt-output {\n\t\t\t\t\tfont-size: 1.16rem;\n\t\t\t\t}\n\n\t\t\t\t.verse-caelum-actions > * {\n\t\t\t\t\twidth: 100%;\n\t\t\t\t}\n\t\t\t}\n\t\t</style><section class=\"verse-caelum-panel verse-panel\"><p class=\"verse-eyebrow\">Prompt</p><div class=\"verse-caelum-prompt mt-4\"><div id=\"prompt\" class=\"verse-caelum-prompt-output italic\">Generate a prompt.</div></div><div class=\"verse-caelum-actions\"><button hx-get=\"/prompt\" hx-target=\"#prompt\" hx-swap=\"innerHTML\" class=\"verse-button\">Generate Prompt</button> <button hx-get=\"/editor\" hx-target=\"#screen\" hx-swap=\"innerHTML\" class=\"verse-button-secondary\">Open Editor</button></div></section></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
